### ISSUE TITLE
PROTOTYPE sprint 4

### ISSUE THREAD

**Issue by kikkiii21** [based-kwl/SemesterPlanner-client#56]
- [x] display friend list, add and remove users #53 #54 #55 
- [x] search page to find users and similar profile suggestions #24 
- [x] tab in nav bar to access friend list #53 
- [x] display academic calendar events #15
